- name: configurar nginx
  hosts: www
  become: True
  roles:
    - nginx

- name: desplegar pagina de bienvenida
  hosts: www
  become: True
  roles:
    - laboratorio-jinja2
  tasks:
    - name: copiar pagina de bienvenida
      template:
        src: templates/megacomplex.html.j2
        dest: /usr/share/nginx/html/index.html
