- name: configurar nginx
  hosts: "tag_Name_MaquinaJordiTomas"
  become: True
  roles:
    - nginx

- name: desplegar pagina de bienvenida
  hosts: tag_Name_MaquinaJordiTomas
  become: True
  tasks:
    - name: copiar pagina de bienvenida
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

